### ISSUE TITLE
make install fails due to missing default.settings.php file

### ISSUE THREAD

**Issue by mikeddeeson** [teamdeeson/d8-quickstart#9]
Hi,

Having created a new project and run `make` followed by `make install` I get the following error when trying to install Drupal:

```
exception 'Drupal\Core\Installer\Exception\InstallerException' with message 'Default settings file: The default settings file does not exist.                           [error]

The Drupal installer requires that the <em class="placeholder">./sites/default/default.settings.php</em> file not be modified in any way from the original download.' in
/var/www/vhosts/d8-t1.dev/web/core/includes/install.core.inc:2168
Stack trace:
#0 /var/www/vhosts/d8-t1.dev/web/core/includes/install.core.inc(1026): install_display_requirements(Array, Array)
#1 /var/www/vhosts/d8-t1.dev/web/core/includes/install.core.inc(660): install_verify_requirements(Array)
#2 /var/www/vhosts/d8-t1.dev/web/core/includes/install.core.inc(538): install_run_task(Array, Array)
#3 /var/www/vhosts/d8-t1.dev/web/core/includes/install.core.inc(115): install_run_tasks(Array)
#4 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#5 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#6 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/commands/core/drupal/site_install.inc(80): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader), Array)
#7 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/commands/core/site_install.drush.inc(249): drush_core_site_install_version(NULL, Array)
#8 [internal function]: drush_core_site_install()
#9 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/includes/command.inc(422): call_user_func_array('drush_core_site...', Array)
#10 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#11 [internal function]: drush_command()
#12 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/includes/command.inc(199): call_user_func_array('drush_command', Array)
#13 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#14 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#15 /var/www/vhosts/d8-t1.dev/vendor/drush/drush/drush.php(12): drush_main()
#16 {main}
```

Having had a look it seems that having the line `"omit-defaults": true` in the composer.json file means that this default file doesn't get downloaded.

Thanks
Mike

**Comment by legolasbo** [comment]
Does #10 work for you @mikeddeeson?

**Comment by mikeddeeson** [comment]
Thanks @legolasbo, I think this would - although it looks like #7 would be a better fix for the moment :)
